name: Update README with Recent Activity

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README with Recent Activity
        uses: joshjohanning/github-activity-readme@v1
        with:
          GH_USERNAME: "Sivamani-18"
          COMMIT_MSG: "Update README with recent activity"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
