name: Recent Activity

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: varunsridharan/github-action@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_USERNAME: Sivamani-18
