name: Update README with Recent Activity

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README with Recent Activity
        uses: Sivamani-18/github-activity-readme@v0.1.1
        with:
          COMMIT_MSG: "Update README with recent activity"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
